<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bharath" failures="1" tests="5" name="Test" time="0.099" errors="0" timestamp="2025-07-28T21:02:54 IST">
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase1" time="0.009">
    <failure type="java.lang.AssertionError" message="Test case 1 failed due to some reason.">
      <![CDATA[java.lang.AssertionError: Test case 1 failed due to some reason.
at testng.framework.concepts.AppCommons.testCase1(AppCommons.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase2" time="0.001"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase3" time="0.008"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase3" time="0.001"/>
  <testcase classname="testng.framework.concepts.AppCommons" name="testCase3" time="0.004"/>
</testsuite> <!-- Test -->
